-- SQLBook: Code
BEGIN;

DROP TABLE IF EXISTS  "user",
    "book",
    "users",
    "books", 
    "univers", 
    "possessed", 
    "want" CASCADE;

CREATE TABLE "univers" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(64) NOT NULL UNIQUE,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE "user" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstname" varchar(64) NOT NULL,
    "lastname" varchar(64) NOT NULL,
    "username" varchar(64) NOT NULL UNIQUE,
    "email" varchar(64) NOT NULL UNIQUE,
    "password" varchar(64) NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz 

);


CREATE TABLE "book" ( 
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar (255) NOT NULL UNIQUE,
    "author" varchar (64) NOT NULL,
    "date_of_publication" date NOT NULL,
    "image" text,
    "summary" text,
    "univers_id" INTEGER NOT NULL REFERENCES "univers"("id"),
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);


CREATE TABLE "possessed" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" integer NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "book_id" integer NOT NULL REFERENCES "book"("id") ON DELETE CASCADE,
    "status" boolean NOT NULL DEFAULT false,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz,
    UNIQUE ("user_id", "book_id")
);

CREATE TABLE "want" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" integer NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
    "book_id" integer NOT NULL REFERENCES "book"("id") ON DELETE CASCADE,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz,
    UNIQUE ("user_id", "book_id")
);






COMMIT;